config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "subscriptions#index"

  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  
  get 'uploads', to: 'videos#new'
  
  post 'signup', to: 'users#create'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  resources :users, except: [:create, :show] do
    # get '/settings', to: 'users#settings'
  end
  
  resources :channel, only: [:show, :edit, :update], path_names: {edit: "settings"}  do
    get '/videos', to: 'channel#videos'
    get '/about', to: 'channel#about'
    
    #ajax
    get 'subcount', to: 'channel#subcount'
    post 'subscribe', to: 'channel#subscribe'
    post 'unsubscribe', to: 'channel#unsubscribe'
  end
  
  resources :videos
  resources :subscriptions
end

app/models/user.rb
class User < ApplicationRecord
  include BCrypt
  
  has_many :videos
  has_many :subscriptions
  
  has_one :channel
  
  after_save :create_channel
  
  validates_presence_of :username
  validates_presence_of :password
  validates_presence_of :email
  
  validates_uniqueness_of :username
  
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  
  serialize :settings
  
  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
  
  def to_param
    username.downcase
  end
  
  def create_channel
    channel = Channel.new
    channel.name = self.username
    channel.user_id = self.id
    channel.unqiue_url = self.username
    channel.save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_username(params[:id])
    @sub_count = Subscription.where(channel_id: @user.id).count
  end

  def new
    @user = User.new
  end

  def edit
    # @user = current_user
    # @settings = @user.settings
  end

  def create
    @user = User.new
    
    if user_params[:password].empty? || user_params[:password_confirmation].empty?
      @user.errors.add(:password, "can't be empty.")
      render 'new'
    else
      if user_params[:password] == user_params[:password_confirmation]
        @user.email = user_params[:email]
        @user.username = user_params[:username]
        @user.password = user_params[:password]
        @user.settings = default_settings
        
        if @user.save
          auth_user(@user.username, user_params[:password])
          flash.notice = "Successfully made account."
          redirect_to root_path
        else 
          render 'new'
        end
      else
        @user.errors.add(:the, 'passwords entered are not the same')
        render 'new'
      end
    end
  end

  def update
  end
  
  private
    def user_params
      params.require(:user).permit!
    end
    
    def default_settings
      []
    end
end

app/views/users/new.html.haml
.large-6.large-centered.columns
  .login-box
    .row.large-12.columns
      %h3 Signup to Video Tube

      .error-container
        = render "shared/errors", errors: @user.errors

      = form_for @user, url: signup_path, data: {abide: ""} do |f|
        .row.large-12.columns
          = f.label :username, "Username"
          = f.text_field :username#, {required: "", :pattern => "[a-zA-Z]+"}
        .row.large-12.columns
          = f.label :email, "Email"
          = f.text_field :email#, {required: ""}
        .row.large-12.columns
          = f.label :password, "Password"
          = f.password_field :password#, {required: ""}
        .row.large-12.columns
          = f.label :password_confirmation, "Confirm Password"
          = f.password_field :password_confirmation#, {required: ""}
        .row.large-12.large-centered.columns
          = f.submit "Sign up", class: "button expanded"

.large-6.large-centered.columns
  .login-box
    .row.large-12.columns
      Already have an account?
      = link_to login_path do
        Login.

app/views/users/show.html.haml
.callout
  #profile-banner
    #banner.remove-padding
      %img{:alt => "image of a planet called Pegasi B", :src => "http://placehold.it/1000x210&text=Pegasi B"}

  #profile-header
    %h2.channel-name
      %strong= @user.channel_username
    #subscribe
      = sub_button
      .count
        .callout
          = number_with_delimiter(@sub_count)

  -# TODO: channel nav bar
  %ul#channel-nav
    = link_to channel_path(@user), class: "selected" do
      %li.selected Home
      
    = link_to channel_videos_path(@user) do
      %li
        Videos
        
    = link_to channel_about_path(@user) do
      %li
        About