config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "subscriptions#index"

  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  
  get 'uploads', to: 'videos#new'
  
  post 'signup', to: 'users#create'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  resources :users, except: [:create, :show] do
    # get '/settings', to: 'users#settings'
  end
  
  resources :channel, only: [:show, :edit, :update], path_names: {edit: "settings"}  do
    get '/videos', to: 'channel#videos'
    get '/about', to: 'channel#about'
    
    #ajax
    get 'subcount', to: 'channel#subcount'
    post 'subscribe', to: 'channel#subscribe'
    post 'unsubscribe', to: 'channel#unsubscribe'
  end
  
  resources :videos
  resources :subscriptions
end

app/models/video.rb
class Video < ApplicationRecord
  require 'securerandom'
  include ActionView::Helpers::DateHelper
  
  belongs_to :channel
  before_save :generate_uid
  
  has_attached_file :video, styles: {
        medium: {
          geometry: "640x480",
          format: 'mp4'
        },
        thumb: { geometry: "1920x1080", format: 'jpeg', time: 10},
        thumb_small: { geometry: "160x120", format: 'jpeg', time: 10}
    }, 
    processors: [:transcoder],
    size: { in: 0..25.megabytes },
    preserve_files: "false"
    
  process_in_background :video  
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
  
  VISIBILITY=['public', 'unlisted', 'private']
  
  def generate_uid
    self.uid ||= SecureRandom.urlsafe_base64(10)
  end
  
  def stats
    "#{views} views • #{time_ago_in_words(self.updated_at).gsub('about', '')} ago"
  end
  
  def status
    if video_processing?.nil?
      'uploading'
    else
      'processing' if video_processing?
      'done' unless video_processing?
    end
  end
  
  def to_param
    self.uid
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @video = Video.find_by(uid: params[:id])
  end
  
  def new
    @video = Video.new
  end
  
  def create
    @video = Video.create(video_params)
    
    if @video.save!
      redirect_to edit_video_path(@video)
    end
  end
  
  def edit
    @video = Video.find_by(uid: params[:id])
    # binding.pry
  end
  
  def update
  end
  
  def status
  end
  
  private
    def video_params
      params.require(:video).permit!
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/edit.html.haml
.callout
  .callout.small.primary
    %p
      - if @video.video_processing?
        Video will be available at 
      - else 
        Video is be available at 
      = link_to video_path(@video) do
        = video_url(@video)

  - if @video.video_processing?
    #status-container
      Uploading
    %progress{:max => "100", :value => "0"}

  = form_for @video do |f|
    = f.label :title
    = f.text_field :title
    
    = f.label :description
    = f.text_area :description
    
    = f.submit "Save changes", class: "button"

app/views/videos/index.html.haml
.callout
  #video-player
    %video#example_video_1.vjs-fluid.video-js.vjs-default-skin.vjs-big-play-centered{controls: "", "data-setup" => "{\"example_option\":true}", poster: "http://vjs.zencdn.net/v/oceans.png", :preload => "auto"}
      %source{:src => "http://vjs.zencdn.net/v/oceans.mp4", :type => "video/mp4"}
      %p.vjs-no-js
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        %a{:href => "http://videojs.com/html5-video-support/", :target => "_blank"} supports HTML5 video
  
  %hr{style: "margin: 15px -15px 20px -15px"}
  %h4= @video.title
  
  .row
    .large-3.columns
      %p{:style => "line-height: 20px;"}
        %img{:src => "https://dummyimage.com/64x64/000/fff&text=icon", :style => "vertical-align: top; padding-right: 5px;"}>
        = @video.channel.channel_name

        #subscribe.float-left{style: "margin-top: -66px; margin-left: 70px;"}
          = sub_button_helper(@video.channel)
          .sub-count
            .callout
              = number_with_delimiter(@sub_count || 0)
    .large-2.columns
      #like-bar
        %p{style: "text-align:right;"}= "#{@video.views} views"
        
  .row.column
    %a.button.hollow.expanded{style: "margin-bottom: 5px;"} Show description

app/views/videos/new.html.haml
.callout
  %h5 Upload
  %hr{style: "margin: 15px -15px 20px -15px"}
  
  = form_for @video do |f|
    = f.file_field :video, class: 'file-input', style: "margin-bottom: 5px;"
    = f.hidden_field :channel_id, value: current_user.channel.id
    -# .button.file-upload
      Choose File

app/views/videos/show.html.haml
.callout
  #video-player
    %video#example_video_1.vjs-fluid.video-js.vjs-default-skin.vjs-big-play-centered{controls: "", "data-setup" => "{\"example_option\":true}", poster: @video.video.url(:thumb), preload: "auto"}
      %source{:src => @video.video.url, :type => "video/mp4"}
      %p.vjs-no-js
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        %a{:href => "http://videojs.com/html5-video-support/", :target => "_blank"} supports HTML5 video
  
  %hr{style: "margin: 15px -15px 20px -15px"}
  %h4= @video.title
  
  .row
    .large-3.columns
      %p{:style => "line-height: 20px;"}
        %img{:src => "https://dummyimage.com/64x64/000/fff&text=icon", :style => "vertical-align: top; padding-right: 5px;"}>
        = @video.channel.channel_name

        #subscribe.float-left{style: "margin-top: -66px; margin-left: 70px;"}
          = sub_button_helper(@video.channel)
          .sub-count
            .callout
              = number_with_delimiter(@sub_count || 0)
    .large-2.columns
      #like-bar
        %p{style: "text-align:right;"}= "#{@video.views} views"
        
  .row.column
    %a.button.hollow.expanded{style: "margin-bottom: 5px;"} Show description