config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "subscriptions#index"

  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  
  get 'uploads', to: 'videos#new'
  
  post 'signup', to: 'users#create'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  resources :users, except: [:create, :show] do
    # get '/settings', to: 'users#settings'
  end
  
  resources :channel, only: [:show, :edit, :update], path_names: {edit: "settings"}  do
    get '/videos', to: 'channel#videos'
    get '/about', to: 'channel#about'
    
    #ajax
    get 'subcount', to: 'channel#subcount'
    post 'subscribe', to: 'channel#subscribe'
    post 'unsubscribe', to: 'channel#unsubscribe'
  end
  
  resources :videos
  resources :subscriptions
end

app/views/layouts/main.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title Video Tube
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .top-bar
      .row
        .top-bar-left
          %ul.menu
            %li
              = link_to root_path do
                Video Tube
            %li
              %input.skinny{:placeholder => "Search", :type => "search"}
            %li
              %button.button.skinny{:type => "button"} Search
        .top-bar-right
          %ul.dropdown.menu{"data-dropdown-menu" => ""}
            - if is_logged_in?
              %li
                = link_to uploads_path do
                  Upload
              %li.has-submenu
                %a{:href => "#"} My Account
                %ul.submenu.menu.vertical{"data-submenu" => ""}
                  %li
                    = link_to channel_path(current_user.channel.unqiue_url) do
                      Channel
                  %li
                    = link_to edit_channel_path(current_user.channel.unqiue_url) do
                      Settings
                  %li
                    = link_to logout_path, method: :post do
                      Logout
            - else
              %li
                = link_to login_path do
                  Upload
              %li
                = link_to login_path do
                  Login

    - if flash.notice
      .flashes.row.column
        .callout.small.success
          %h5= flash.notice
    - if flash.alert
      .flashes.row.column
        .callout.small.alert
          %h5= flash.alert

  #content
    .row.column
      = yield